### ISSUE TITLE
Rev HtmlAgilityPack Version

### ISSUE THREAD

**Issue by grock90** [JustinGrote/PowerHTML#4]
Update to latest version of the HtmlAgilityPack assemblies v1.11.16

Possible solution:  Use package management to download NuGet package for HtmlAgilityPack assemblies.

**Comment by JustinGrote** [comment]
Pushed, seems to work for me:
https://www.powershellgallery.com/packages/PowerHTML/0.1.7

I'll rig this up to dependabot if I get some time to automatically rev the dependency as new versions are released.

**Comment by grock90** [comment]
Confirmed it's working, thanks for the rev update.
